#ifndef VERSION_H
#define VERSION_H

#define VERSION "0.15.0-dev"

#define HISTORY_MAGIC_NUMBER 0x84D3C117
#define HISTORY_VERSION 3

#define PROTO_MAGIC_NUMBER 0x84D3C117
#define PROTO_VERSION 4

#define CONFIG_VERSION 2

#define DISCOVERY_PORT 9999

#define VERIFICATION_TRIES 5

#define SOCKET_NAME "haveclip.sock"

#endif // VERSION_H
