#ifndef VERSION_H
#define VERSION_H

#define VERSION "0.13.0"

#define HISTORY_MAGIC_NUMBER 0x84D3C117
#define HISTORY_VERSION 3

#define PROTO_MAGIC_NUMBER 0x84D3C117
#define PROTO_VERSION 4

#define CONFIG_VERSION 2

#define DISCOVERY_PORT 9999

#endif // VERSION_H
